import os
from langchain import OpenAI, ConversationChain, LLMChain, PromptTemplate
from langchain.memory import ConversationBufferWindowMemory
from dotenv import load_dotenv
from langchain.memory import VectorStoreRetrieverMemory
from langchain.embeddings import OpenAIEmbeddings
from langchain.chat_models import ChatOpenAI

load_dotenv()

# Initialize an empty list to store the conversation history
conversation_history = []


def conversation(human_input):
    """
    Conducts a conversation with the Assistant language model.

    This function takes a human input, processes it using the Assistant language model, and returns the response
    generated by the model. The Assistant is a large language model trained by OpenAI.

    Args:
        human_input (str): The input text provided by the human user.
    
    Returns:
        str: The response generated by the Assistant language model.

    """

    template = """Assistant is a large language model trained by  OpenAI.

    Assistant is designed to be able to assist with a wide range of tasks, from answering simple questions to providing in-depth explanations and discussions on a wide range of topics. As a language model, Assistant is able to generate human-like text based on the input it receives, allowing it to engage in natural-sounding conversations and provide responses that are coherent and relevant to the topic at hand.

    Assistant is constantly learning and improving, and its capabilities are constantly evolving. It is able to process and understand large amounts of text, and can use this knowledge to provide accurate and informative responses to a wide range of questions. Additionally, Assistant is able to generate its own text based on the input it receives, allowing it to engage in discussions and provide explanations and descriptions on a wide range of topics.

    Overall, Assistant is a powerful tool that can help with a wide range of tasks and provide valuable insights and information on a wide range of topics. Whether you need help with a specific question or just want to have a conversation about a particular topic, Assistant is here to assist.

    {history}
    Human: {human_input}
    Assistant:"""

    # Join the conversation history using newline character '\n'
    history = "\n".join(conversation_history)

    prompt = PromptTemplate(
        input_variables=["history", "human_input"],
        template=template
    )

    chatgpt_chain = LLMChain(
        llm=OpenAI(temperature=0),
        prompt=prompt,
        verbose=True,
    )

    # Append the user input to the conversation history
    conversation_history.append(f"Human: {human_input}")

    output = chatgpt_chain.predict(history=history, human_input=human_input)
    return output
